language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: '5.6'
    - php: '7.0'
    - php: '7.1'
    - php: nightly

install:
  - composer install
