language: php
php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.1'
    - php: nightly

before_script:
  - pecl channel-update pecl.php.net
  - pecl install uopz
  - composer install
