language: php
php:
  - '7.1'
  - '7.2'
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: '7.1'
    - php: nightly

install:
  - composer install

before_script:
  - sudo pecl install uopz
  
